# Generated by Django 3.2.6 on 2021-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer_Buyer_Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=20)),
                ('buyer_id', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='farmer_wh_owner_connection',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
