# Generated by Django 2.2.12 on 2021-11-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_connections', '0002_auto_20211118_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_buyer_connection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farmer_wh_owner_connection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
