# Generated by Django 3.2.7 on 2021-11-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_connections', '0003_auto_20211118_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_buyer_connection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='farmer_wh_owner_connection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
