# Generated by Django 3.2.6 on 2021-11-21 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer_connections', '0004_auto_20211118_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer_wh_owner_connection',
            name='farmer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmer_wh_owner_connection',
            name='status',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='farmer_wh_owner_connection',
            name='wh_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
