# Generated by Django 3.2.7 on 2021-11-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.IntegerField()),
                ('Subscription_id', models.CharField(max_length=300)),
                ('TotalAmount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubscriptionType', models.CharField(max_length=300, unique=True)),
                ('NumberofDuration', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
    ]
