# Generated by Django 3.1.5 on 2021-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmers',
            name='image',
            field=models.ImageField(default=0.00024850894632206757, upload_to='pics'),
            preserve_default=False,
        ),
    ]
