# Generated by Django 3.2.7 on 2021-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
