# Generated by Django 3.2.7 on 2021-11-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0003_alter_farmers_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmers',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='farmers',
            name='title',
        ),
        migrations.AddField(
            model_name='farmers',
            name='Contacts',
            field=models.IntegerField(default=20, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmers',
            name='Location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmers',
            name='Price_per_kilo',
            field=models.IntegerField(default=50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmers',
            name='produce',
            field=models.CharField(default=56, max_length=100),
            preserve_default=False,
        ),
    ]
