# Generated by Django 3.2.7 on 2021-11-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_auto_20211121_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='Contacts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='farmers',
            name='Price_per_kilo',
            field=models.IntegerField(),
        ),
    ]
