# Generated by Django 3.2.7 on 2021-11-19 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehousename', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('storagefee', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('contacts', models.IntegerField()),
                ('image', models.FileField(upload_to='pics/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
