# Generated by Django 3.2.7 on 2021-11-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouses',
            name='image',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
