# Generated by Django 3.2.7 on 2021-11-18 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='user_id',
        ),
        migrations.AddField(
            model_name='upload',
            name='user',
            field=models.ForeignKey(default=0.0004955401387512388, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
